### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by neilenns** [neilenns/clearancelab#192]
```yaml
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.22.1
    hooks:
      - id: gitleaks
        name: "🔒 security · Detect hardcoded secrets"
```

https://gatlenculp.medium.com/effortless-code-quality-the-ultimate-pre-commit-hooks-guide-for-2025-57ca501d9835
https://pre-commit.com/
