### ISSUE TITLE
Fix turbo --affected to actually work

### ISSUE THREAD

**Issue by neilenns** [neilenns/clearancelab#86]
https://github.com/vercel/turborepo/issues/9320

Maybe try this again:

```yaml
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          filter: "blob:none"
          fetch-depth: 0
```
